include:
  - compose.base.yml

services:
  server:
    build:
      context: ./server
      dockerfile: ./Dockerfile.dev
    ports:
      - 3001:3001
    env_file:
      - ./server/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mlc?schema=public"
      WATCHPACK_POLLING: true
    depends_on:
      postgres:
        condition: service_started
      init-db-from-snapshot:
        condition: service_completed_successfully 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/v1/health"]
      interval: 1s
      timeout: 200ms
      retries: 3
      start_period: 1s
    develop:
      watch:
        - action: rebuild
          path: ./server
          include:
            - .env
            - "Dockerfile*"
            - package-lock.json

        - action: sync
          path: ./server
          target: /opt/server
          ignore:
            - "Dockerfile*"
            - .vs/
            - .vscode/
            - node_modules/
            - dist/
            - "*.log"
            - package.json
            - package-lock.json

  frontend:
    stdin_open: true
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      server:
        condition: service_healthy
    develop:
      watch:
        - action: rebuild
          path: ./frontend
          include:
            - .env
            - "Dockerfile*"
            - package-lock.json

        - action: sync
          path: ./frontend
          target: /opt/app
          ignore:
            - "Dockerfile*"
            - .vs/
            - .vscode/
            - node_modules/
            - dist/
            - "*.log"
            - package.json
            - package-lock.json
