include:
  - compose.base.yml

services:
  mlc-backend:
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    ports:
      - 4001:3001
    env_file:
      - ./apps/backend/.env
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/mlc?schema=public"
      WATCHPACK_POLLING: true
    depends_on:
      postgres:
        condition: service_started
      init-db-from-snapshot:
        condition: service_completed_successfully 
    develop:
      watch:
        - action: rebuild
          path: ./apps/backend
          include:
            - .env
            - "Dockerfile*"
            - package.json 

        - action: sync
          path: ./packages
          target: /opt/mlc/packages
          ignore:
            - "**/node_modules"

        - action: sync
          path: ./apps/backend
          target: /opt/mlc/apps/backend
          ignore:
            - "Dockerfile*"
            - dist/
            - "*.log"
            - package.json
            - node_modules

  mlc-frontend:
    stdin_open: true
    build:
      context: .
      dockerfile: ./apps/frontend/Dockerfile
    ports:
      - 4000:5173
    depends_on:
      mlc-backend:
        condition: service_started
    develop:
      watch:
        - action: rebuild
          path: ./apps/frontend
          include:
            - .env
            - "Dockerfile*"
            - package.json 

        - action: sync
          path: ./packages
          target: /opt/mlc/packages
          ignore:
            - "**/node_modules"

        - action: sync
          path: ./apps/frontend
          target: /opt/mlc/apps/frontend
          ignore:
            - "Dockerfile*"
            - dist/
            - "*.log"
            - package.json
            - node_modules
