services:
  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=mlc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  init-db-from-snapshot:
    image: alpine:3.18
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db:/var/run/db
    command: >
      /bin/sh -c "
        if [ -f /var/run/db/db_init.tar ]; then
          apk update && apk add postgresql13-client &&

          export PGPASSWORD=postgres &&
          /usr/libexec/postgresql13/pg_restore -h postgres -U postgres -p 5432 -d mlc --verbose /var/run/db/db_init.tar
        else
          echo 'Database restore file not found, skipping...'
        fi
        
        exit 0
      "

