FROM node:22-bullseye-slim

RUN apt-get update && apt-get install -y curl

USER node
WORKDIR /opt/server

COPY --chown=node:node package*.json ./

RUN npm install

COPY --chown=node:node . ./

RUN chmod 777 \
  ./uploads/ideaImage \
  ./uploads/adImage \
  ./uploads/avatarImages \
  ./prisma/migrations \
  ./prisma/migrations/migration_lock.toml

RUN npm run prisma:generate

ENV NODE_ENV=development

EXPOSE 3001
CMD ["npx", "nodemon", "-L", "--watch", ".", "server.js"]
