name: Retarget Dependabot Security PRs
on:
  pull_request:
    types: [opened]

jobs:
  retarget:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Change target branch
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              base: 'security-patches'
            })
